apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.evaluation.triggered
      requests:
        - curl --request GET http://mongodb-datastore.pia21048:8080/health
      subscriptionID: e949c2ff-d1c2-48a5-b252-7de28600cbe8
      sendFinished: true
