apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.evaluation.triggered
      requests:
        - curl --request GET https://kubernetes.default.svc
      subscriptionID: b65ff415-3ca1-469b-9cd3-48d33aa88604
      sendFinished: true
